name: Build and Push Image

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *" # Everyday at 2am
  workflow_dispatch:

env:
  DOCKER_IMAGE: arranhs/closedagent

jobs:
  get-calver:
    name: Get CalVer
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      calver: ${{ steps.get-date.outputs.calver }}

    steps:
      - name: Get date
        id: get-date
        run: |
          CALVER=$(date -u +"%Y.%m.%d")

          echo "calver=$CALVER" >> $GITHUB_OUTPUT

          echo "
          CalVer: $CALVER
          "

  build:
    name: Build Image

    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            platform-slug: linux-amd64

          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            platform-slug: linux-arm64

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ${{ env.DOCKER_IMAGE }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p "$DIGESTS_DIR"
          touch "$DIGESTS_DIR/${DIGEST#sha256:}"
        env:
          DIGESTS_DIR: ${{ runner.temp }}/digests
          DIGEST: ${{ steps.build.outputs.digest }}

      - name: Upload digest
        uses: actions/upload-artifact@v6
        with:
          name: digest-${{ matrix.platform-slug }}
          path: ${{ runner.temp }}/digests/*
          retention-days: 1

  merge-digests:
    name: Merge Digests
    runs-on: ubuntu-latest
    needs: [get-calver, build]
    timeout-minutes: 10

    steps:
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Download digests
        uses: actions/download-artifact@v7
        with:
          pattern: digest-*
          path: ${{ runner.temp }}/digests
          merge-multiple: true

      - name: Push docker manifest
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create \
            -t "$DOCKER_IMAGE:latest" \
            -t "$DOCKER_IMAGE:$CALVER" \
            $(printf "$DOCKER_IMAGE@sha256:%s " *)
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          CALVER: ${{ needs.get-calver.outputs.calver }}
