name: Docker

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build.yaml
      - Dockerfile
      - entrypoint.d/**
      - scripts/**
  schedule:
    - cron: "0 12 * * *" # Everyday at 12am
  workflow_dispatch:
    inputs:
      no-cache:
        description: Disable docker build cache
        type: boolean
        default: false

env:
  DOCKER_IMAGE: arranhs/closedagent

jobs:
  get-calver:
    name: Get CalVer
    runs-on: ubuntu-latest
    timeout-minutes: 10

    outputs:
      calver: ${{ steps.get-date.outputs.calver }}

    steps:
      - name: Get date
        id: get-date
        run: |
          CALVER=$(date -u +"%Y.%m.%d")

          echo "calver=$CALVER" >> $GITHUB_OUTPUT

          echo "
          CalVer: $CALVER
          "

  build:
    name: Build Image
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-24.04
            platform: linux/amd64
            platform-slug: linux-amd64

          - runner: ubuntu-24.04-arm
            platform: linux/arm64
            platform-slug: linux-arm64

    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          tags: ${{ env.DOCKER_IMAGE }}
          cache-from: ${{ !inputs.no-cache && 'type=gha' || '' }}
          cache-to: ${{ !inputs.no-cache && 'type=gha,mode=max' || '' }}
          outputs: type=image,push-by-digest=true,name-canonical=true,push=true

      - name: Output digest
        uses: GoCodeAlone/github-action-matrix-outputs-write@1.0.3
        with:
          matrix-step-name: build
          matrix-key: ${{ matrix.platform-slug }}
          outputs: |
            digest: ${{ steps.build.outputs.digest }}

  push-tags:
    name: Push Tags
    runs-on: ubuntu-latest
    needs: [get-calver, build]
    timeout-minutes: 10

    steps:
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get digests
        id: get-digests
        uses: GoCodeAlone/github-action-matrix-outputs-read@1.0.6
        with:
          matrix-step-name: build

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push tags
        run: |
          DIGESTS=$(
            echo "$DIGESTS_JSON" |
            jq -r --arg docker_image "$DOCKER_IMAGE" \
              '.digest | to_entries[] | "\($docker_image)@\(.value)"'
          )

          docker buildx imagetools create \
            -t "$DOCKER_IMAGE:latest" \
            -t "$DOCKER_IMAGE:$CALVER" \
            $DIGESTS
        env:
          DIGESTS_JSON: ${{ steps.get-digests.outputs.result }}
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
          CALVER: ${{ needs.get-calver.outputs.calver }}
